### ISSUE TITLE
Home Page Header

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#1]
The design of the thread in the Header is a mismatch. 

The thread can be cut short to fix the shortest word in the header
![header thread](https://user-images.githubusercontent.com/50691503/57999030-91014f80-7af1-11e9-8bef-bf0fe0bddb3e.PNG)

**Comment by Honeybbs** [comment]
Second Band/ Banner Placement and text alignment as er the shared design. 
![home page- band 1 correction](https://user-images.githubusercontent.com/50691503/57999949-dd01c380-7af4-11e9-8832-d561e9e27413.PNG)
![home page- band 1](https://user-images.githubusercontent.com/50691503/57999950-dd01c380-7af4-11e9-89a5-ba6afecb9773.PNG)

**Comment by Honeybbs** [comment]
Third Band on the Home Page-
 Underlining of the steps with the thread- thread design is a mismatch. Image of the thread needs to be optimized as per the length of the word. 
![band 3 thread](https://user-images.githubusercontent.com/50691503/58001019-f9532f80-7af7-11e9-900d-5fa7804b1bfd.PNG)

Correction:
![band 3 thread correction](https://user-images.githubusercontent.com/50691503/58001151-4df6aa80-7af8-11e9-8071-1a205422bdba.PNG)

Font size and Font Style, Color also needs to be as per the PSD

**Comment by iamvivekkaushik** [comment]
@iamhssingh there are no threads in the footer.
@Honeybbs please clarify this, thread in the header can be cut to match the length of word?

**Comment by Honeybbs** [comment]
@iamvivekkaushik I rectified, it was header only, the schreenshot of the same was attached.
