### ISSUE TITLE
Product Page- Banner 2

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#12]
Background and font style of the text in the banner needs to be as per the PSD. 

Current design on the website-
![about Us- Banner 2](https://user-images.githubusercontent.com/50691503/58090709-7e684280-7be5-11e9-8bdb-4770e1b6d184.PNG)

Correct design asper the PSD:

![product page- banner 2](https://user-images.githubusercontent.com/50691503/58090763-a657a600-7be5-11e9-9037-1149235f27a5.PNG)

**Comment by iamvivekkaushik** [comment]
PSD received

![productTop](https://user-images.githubusercontent.com/10868176/58093528-516b5e00-7bec-11e9-90e5-0dc3e45085eb.jpg)
