### ISSUE TITLE
Product Page- Product Listing

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#13]
All products to be displaced in the same page, not in the slider form. (As per the PSD)

Caption (font style, color) of the products to be as per the PSD. 
Reduce the line spacing in the caption. 
Size of the awards and certificate boxes to be reduced, needs to be as per the PSD. 

NOTE: Please follow the font style, size and color as per the PSD. This has to be mentioned in all issues for all the pages. 
![Products Page- Products Display](https://user-images.githubusercontent.com/50691503/58092340-73afac80-7be9-11e9-9638-f30fc585597f.PNG)

Correct design:
![correct products page- Products display](https://user-images.githubusercontent.com/50691503/58092441-ba050b80-7be9-11e9-8896-1829c3427c6f.PNG)

**Comment by iamvivekkaushik** [comment]
@iamhssingh received different psd
![productSliderPSD](https://user-images.githubusercontent.com/10868176/58093299-d609ac80-7beb-11e9-8b78-4a371595e820.jpg)

**Comment by Honeybbs** [comment]
@iamvivekkaushik and @iamhssingh Please share the PSD with me as and when received by you at corporatesales@babysaffron.com
