### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#16]
Contact Us Page- Inquiry Panel Placement. 

Current design on the website:

![Contact us Page](https://user-images.githubusercontent.com/50691503/58248772-a4731b80-7d7a-11e9-90cd-4e192b26614f.PNG)

Correct Design as per the PSD:

![Correct Contact us Page](https://user-images.githubusercontent.com/50691503/58248783-b0f77400-7d7a-11e9-8128-29a25ced80e2.PNG)

The panel need to be pushed up to be placed partially over the Map as per the PSD.

**Comment by iamvivekkaushik** [comment]
@iamhssingh please check this.

Current Website Design:
![Screenshot_2019-05-28 Baby Saffron](https://user-images.githubusercontent.com/10868176/58477259-b8e75780-8170-11e9-91fd-71af36da1a53.png)

Design Recieved:
![Contact us page](https://user-images.githubusercontent.com/10868176/58477285-c270bf80-8170-11e9-8334-e029347eaaca.jpg)
