### ISSUE TITLE
Home Page Band-4

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#4]
Band -4 Background Image, Size of the banner as per the given design. 

Current design on the website: 

![band-4](https://user-images.githubusercontent.com/50691503/58001608-95ca0180-7af9-11e9-92b3-3d3de30dc385.PNG)
 
Correct Design:

![correct band-4](https://user-images.githubusercontent.com/50691503/58001754-05d88780-7afa-11e9-8591-e62a512cb72c.PNG)

**Comment by iamvivekkaushik** [comment]
@Honeybbs need the background Image

**Comment by Honeybbs** [comment]
@iamvivekkaushik you can go ahead with the same image for now, we will be uploading the relevant image later. will we able to adjust the size of the same??
