### ISSUE TITLE
Home Page- Recipe Band

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#5]
Home Page Recipe Band- 

Size of the band, font size, font style and alignment of the headings and text. 
Current design on the website-
![recipe banner](https://user-images.githubusercontent.com/50691503/58006370-92d50e00-7b05-11e9-80f6-1c44c76acbc9.PNG)

Correct design as per the PSD:

![correct recipe band](https://user-images.githubusercontent.com/50691503/58006655-30c8d880-7b06-11e9-8b87-377635ef2927.PNG)

**Comment by iamvivekkaushik** [comment]
PSD Received

![home_design_psd_old](https://user-images.githubusercontent.com/10868176/58094108-7f04d700-7bed-11e9-9cad-d85186ca7aad.jpg)
