### ISSUE TITLE
Home Page- Products Banner

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#6]
Alignment of the text in the banner, font size, font style needs to be as per the PSD. 
![our products banner](https://user-images.githubusercontent.com/50691503/58011999-1811f000-7b11-11e9-9972-1325760bca8b.PNG)

**Comment by iamhssingh** [comment]
@iamvivekkaushik can you please upload the PSD version here?

**Comment by iamvivekkaushik** [comment]
Home page psd design
![psd_home_product](https://user-images.githubusercontent.com/10868176/58012563-607ddd80-7b12-11e9-81e4-7c61a9f576d7.jpg)

**Comment by iamhssingh** [comment]
@Honeybbs please confirm following are the changes you are asking for in this page:
- [ ] Reduce spacing between products
- [ ] Add Left/Right arrows in the slider
- [ ] Change color of the product name to greyish
- [ ] Increase spacing between product name & product price
- [ ] Change font for `Our Products`

@iamvivekkaushik if you have any confusion regarding font size/style/color, please ask here and get the specific detail.

**Comment by Honeybbs** [comment]
As per the PSD provided by Vivek, the changes have to be done. It is impossible for me to specifically mention each and every edit separately.  You can clearly make out the difference between the PSD and the design uploaded on the website.

**Comment by iamhssingh** [comment]
> As per the PSD provided by Vivek, the changes have to be done. It is impossible for me to specifically mention each and every edit separately. You can clearly make out the difference between the PSD and the design uploaded on the website.

@Honeybbs sure. That is not a problem. Please add if I have missed something in the list.
