### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by Honeybbs** [civilmachines/BabySaffron-Bug-Tracker#8]
Image for the "vision"- shared on email

Image for the "mission"- shared on email

Font alignment of the text- as per the PSD

Current design on the website-

![about us vsion mission](https://user-images.githubusercontent.com/50691503/58016645-cb7fe200-7b1b-11e9-957a-e4aeedc85332.PNG)

 Correct website Design-
![correct mission vision](https://user-images.githubusercontent.com/50691503/58016687-eeaa9180-7b1b-11e9-848b-acefca990c3f.PNG)

**Comment by iamvivekkaushik** [comment]
@iamhssingh need those images for vision and mission

**Comment by iamvivekkaushik** [comment]
PSD Received by us

![About-Us-Page_1](https://user-images.githubusercontent.com/10868176/58229675-f6527c00-7d4f-11e9-87b1-2f270bba6463.jpg)

**Comment by Honeybbs** [comment]
![heart](https://user-images.githubusercontent.com/50691503/58540716-965c4980-8217-11e9-8e4e-439c58ca0e03.png)

@iamvivekkaushik can you try using this image for the vision? if it works will provide one for mission as well.
